### ISSUE TITLE
Publish last version of code in maven central

### ISSUE THREAD

**Issue by gleb619** [j-easy/easy-props#12]
As i see, there was very usefull commit for environment variables support https://github.com/j-easy/easy-props/commit/dbd58e0a76965b206ad2bc020124ec2eb9b242e9
But this code missing in version 2.0.1, which could be found in maven central.

Can anybody help me with this?

**Comment by benas** [comment]
Hi @gleb619 ,

Sorry for the late reply on this. Indeed this feature has been merged but is not released yet. I'm planning to release v3.0.0 soon which will contain this feature.

I will let you know once its released here. Keep tuned 😉

**Comment by gleb619** [comment]
Super!

**Comment by benas** [comment]
Hi @gleb619 ,

I just wanted to let you know that v3.0.0 has been released and includes the new environment variable annotation: https://github.com/j-easy/easy-props/releases/tag/easy-props-3.0.0

Enjoy 😉 
Mahmoud
