### ISSUE TITLE
Add ability to fail fast by throwing an exception if a property is absent

### ISSUE THREAD

**Issue by ashtttt** [j-easy/easy-props#14]
I am trying to use @EnvironmentVariable annotation, currently if annotated environment variable is not set in the deployed environment the fields are left with "null" value.
I can see we have option to set a default value, can we also have an option to throw an exception if a given environment variable is not set. This allows us to fail the applications during  configuration initialization.

**Comment by benas** [comment]
Makes sense, as there is no way to fail fast currently. This can actually be added to all annotations. Let me plan this for next release. Thank you for raising  this issue!

**Comment by benas** [comment]
@ashtttt I added the ability to fail fast by throwing an exception if an environment variable is not set:

```java
class Bean {
     @EnvironmentVariable(value = "absent", failFast = true)
     private String absentValue;
}
```

You can try it already with v3.1.0-SNAPSHOT.

Thank you for raising this issue!
