### ISSUE TITLE
Prefix db properties with org.jeasy.props

### ISSUE THREAD

**Issue by fmbenhassine** [j-easy/easy-props#25]
As of v3.1, database properties used by the `DBPropertyAnnotationProcessor` are expected to be named like `db.driver`, `db.url`, etc. This is error prone as those names are generic and might be used for other purposes. Those properties are better prefixed with `org.jeasy.props` to prevent any ambiguity.

**Comment by benas** [comment]
Resolved in ddbc1cbcccd9295280e35c9c1dcd0154d5bd6c2f.
