### ISSUE TITLE
configuration through Consul feature request

### ISSUE THREAD

**Issue by yisraelU** [j-easy/easy-props#6]
I would like to request that compatibility be added in for configuration management tools such as consul or etcd. 
They both have a decent http API .
I'm thinking something along the lines of a core configuration through http and layers for specific software.
thank you

**Comment by benas** [comment]
Hi,

Could you please elaborate more on "compatibility be added in for configuration management tools such as consul or etcd" ? I'm not sure I understand this point.

Please give examples to help me understand your point.

Kr
Mahmoud

**Comment by yisraelU** [comment]
sure.
currently easy props can load configurations from multiple sources such as
a  file,database etc..
I would like if there was support to load configurations from Consul and
Etcd which provide a k/v store for configuration and watch for changes and
push them out

**Comment by benas** [comment]
Thanks, I see. Interesting idea!

I'm thinking of a custom annotation and processor (see example in the [wiki](https://github.com/j-easy/easy-props/wiki/Custom-Annotations)), something like:

```java
@EtcdProperty(key = "size")
private int size;
```

The custom processor may use a java driver like [jetcd](https://github.com/coreos/jetcd).

What do you think?

**Comment by yisraelU** [comment]
sure, Consul has a few custom drivers as well like 
 http://www.cfg4j.org.

**Comment by benas** [comment]
cfg4j is an entire library, we only need a a consul driver if we want to add a consul extension for easy-props. (same for etcd)

BTW, we can develop this is a separate module as an extension for a third party config provider. Do you want to contribute? It is a single interface to implement. You are welcome.

**Comment by yisraelU** [comment]
would definitely love to give it a go. Just the single interface needs to
be implemented?

**Comment by benas** [comment]
Yes, you can follow the steps described in the wiki: https://github.com/j-easy/easy-props/wiki/Custom-Annotations

I suggest you provide a custom annotation/processor for etcd using the official java driver (in a separate module). I would be happy to merge it!

Kind regards
Mahmoud

**Comment by yisraelU** [comment]
Ok . Will get started

**Comment by benas** [comment]
@yisraelU I'm closing this issue for now. If you want to contribute a plugin for etcd, your are welcome! In this case, please open a PR referencing this issue.
